name: Deploy to Personal VPS

#! Since this is a public repository, DO NOT use a job that runs on pull request
on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy Personal Blog
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Build and deploy compose file
        run: |
          docker-compose down
          docker-compose up -d --build
